#!/bin/ksh

# Adapt this to point to the path of the onnx local copy
# by default: cd && git clone https://github.com/onnx/onnx
ONNX_CHECKOUT_DIR=$HOME/onnx
export OP=$1
OP="$(tr '[:lower:]' '[:upper:]' <<< ${OP:0:1})${OP:1}"

(
cat <<EOF
package operators

import (
	onnx "github.com/owulveryck/onnx-go"
	"gorgonia.org/gorgonia"
)

// $OP operator
// https://github.com/onnx/onnx/blob/master/docs/Operators.md#$OP
type $OP struct {
	name string
}

// Init ...
func (o *$OP) Init(attrs []*onnx.AttributeProto) error {
	o.name = "$OP"
      return &onnx.ErrNotImplemented{
			Operator:       o.name,
			Message:        "Not implemented yet",
		}
}

// Apply ...
func (o *$OP) Apply(input ...*gorgonia.Node) ([]*gorgonia.Node, error) {
/*
	if len(input) != 2 {
		return nil, &ErrBadArity{
			Operator:      o.name,
			ExpectedInput: 2,
			ActualInput:   len(input),
		}
	}
      */
      return nil, &onnx.ErrNotImplemented{
			Operator:       o.name,
			Message:        "Not implemented yet",
		}

}
EOF
) | goimports > ${1}_todo.go
go run ../utilities/tests_gen/*go -op $1 -testpath ${ONNX_CHECKOUT_DIR}/onnx/backend/test/data/node/ > ${1}_autogenerated_test.go
